//! The C ABI a Brass plugin exposes to the host.
//!
//! A plugin is a `cdylib` exporting three `extern "C"` symbols (generated by
//! [`crate::brass_lib!`]):
//!
//! - `brass_entry(host_abi: u32) -> *const RawManifest` -- build the
//!   registry once and return the function manifest. Returns null when the
//!   host's ABI version is one the plugin cannot serve.
//! - `brass_call(index: u32, args: *const RawValue, argc: usize,
//!   out: *mut RawValue) -> i32` -- invoke function `index` from the manifest.
//!   Argument values (and any buffers they point to) are owned by the host and
//!   valid only for the duration of the call. On [`CALL_OK`] / [`CALL_ERR`],
//!   `out` holds the result / the error message; any buffer it points to is
//!   owned by the plugin and stays valid until the host passes the value to
//!   `brass_release`.
//! - `brass_release(value: RawValue)` -- reclaim a buffer-carrying value the
//!   plugin returned through `out`.
//!
//! Everything crossing the boundary is `#[repr(C)]` and self-describing, so a
//! host and a plugin built by different compiler versions interoperate as long
//! as [`ABI_VERSION`] matches.

/// Version of this boundary. The host refuses a manifest with a different
/// version, so an incompatible plugin fails at load with a clear message
/// instead of corrupting memory.
pub const ABI_VERSION: u32 = 2;

/// `brass_call` statuses.
pub const CALL_OK: i32 = 0;
/// The call failed with a plugin-level error; `out` is a [`TAG_STRING`]
/// message. The host surfaces it as a Brass `Result` error.
pub const CALL_ERR: i32 = 1;
/// The index/argument list did not match the manifest (a host bug or a stale
/// manifest); `out` is untouched.
pub const CALL_BAD: i32 = 2;

/// [`RawValue::tag`] values.
pub const TAG_VOID: u32 = 0;
pub const TAG_BOOL: u32 = 1;
pub const TAG_INT: u32 = 2;
pub const TAG_FLOAT: u32 = 3;
/// UTF-8 text in `ptr`/`len`.
pub const TAG_STRING: u32 = 4;
/// Raw bytes in `ptr`/`len` (Brass `uint8[]`, encoded densely).
pub const TAG_BYTES: u32 = 5;
/// `len` [`RawValue`]s at `ptr`: any other array, nesting to any depth.
pub const TAG_ARRAY: u32 = 6;

/// One dynamically-typed value crossing the boundary. Exactly one of the
/// payload fields is meaningful, selected by `tag`; the others are zero.
#[repr(C)]
#[derive(Clone, Copy)]
pub struct RawValue {
    pub tag: u32,
    /// [`TAG_BOOL`] (0/1) and [`TAG_INT`].
    pub int: i64,
    /// [`TAG_FLOAT`].
    pub float: f64,
    /// The buffer of a `ptr`/`len` tag: bytes for [`TAG_STRING`] /
    /// [`TAG_BYTES`], or `len` [`RawValue`]s (cast) for [`TAG_ARRAY`].
    pub ptr: *const u8,
    pub len: usize,
}

impl RawValue {
    pub const fn void() -> Self {
        RawValue {
            tag: TAG_VOID,
            int: 0,
            float: 0.0,
            ptr: core::ptr::null(),
            len: 0,
        }
    }
}

/// A borrowed UTF-8 string in the manifest. The bytes live inside the plugin
/// and stay valid for the plugin's lifetime; the host copies what it keeps.
#[repr(C)]
#[derive(Clone, Copy)]
pub struct RawStr {
    pub ptr: *const u8,
    pub len: usize,
}

impl RawStr {
    /// # Safety
    /// `ptr`/`len` must describe a live UTF-8 buffer.
    pub unsafe fn as_str<'a>(&self) -> &'a str {
        if self.len == 0 {
            return "";
        }
        unsafe { core::str::from_utf8_unchecked(core::slice::from_raw_parts(self.ptr, self.len)) }
    }
}

/// One exported function in the manifest.
#[repr(C)]
pub struct RawFunction {
    /// The name Brass imports (`import lib.{ name }`).
    pub name: RawStr,
    /// Doc comment (markdown prose); empty when the function has none.
    pub doc: RawStr,
    /// Signature encoding: each parameter's
    /// [type code](crate::value::ValueType::code) in order, `:`, the return
    /// type's code, and a trailing `!` when the function is fallible (maps to
    /// Brass `-> T!`). A code is one letter per leaf type, `a` prefixed per
    /// array level, so it is self-delimiting. E.g. `"ii:i"`, `"s:s!"`,
    /// `":v"`, `"ass:s"` (`(string[], string) -> string`).
    pub sig: RawStr,
    /// Parameter names, comma-joined (`"a,b"`); shown by editor tooling.
    pub param_names: RawStr,
    /// The index to pass to `brass_call`.
    pub index: u32,
}

/// The table `brass_entry` returns. Lives inside the plugin for the
/// plugin's lifetime.
#[repr(C)]
pub struct RawManifest {
    /// The plugin's [`ABI_VERSION`]; the host rejects a mismatch.
    pub abi: u32,
    pub fn_count: usize,
    pub fns: *const RawFunction,
}
