//! Shared front-end module loading: the embedded standard-library prelude, the
//! byte-offset `SourceMap` that keeps every file's spans globally unique, and
//! the transitive import loader.
//!
//! Both front ends -- the CLI driver and the language server -- assemble the
//! same module graph; this module is their single implementation. They differ
//! only in policy: the driver aborts on load errors while the language server
//! surfaces them as diagnostics and keeps analyzing, so the loader COLLECTS
//! [`LoadError`]s (attributed to the triggering import's span in the entry
//! file) and lets each caller decide.

use std::collections::{HashMap, HashSet};
use std::path::{Path, PathBuf};

use brass_hir::LoadedModule;
use brass_parser::ast::{
    Expr, ImportDecl, ImportedName, Module, Pattern, Stmt, StrSeg, TopLevel, TypeExpr,
};
use brass_parser::parse_with_base;
use brass_parser::{Span, line_col};

// `STDLIB` (the implicit prelude, every `std/prelude/*.cz`) and
// `STDLIB_NESTED` (the import-only modules, every other `.cz` under `std/`).
// The tables are generated by build.rs from the actual `std/` tree, so adding
// a standard-library module is just adding a file.
include!(concat!(env!("OUT_DIR"), "/stdlib.rs"));

/// Names of the embedded top-level prelude modules (`io`, `array`, ...), used by
/// import-path completion.
pub fn prelude_module_names() -> impl Iterator<Item = &'static str> {
    STDLIB.iter().map(|(name, _)| *name)
}

/// The source of an embedded prelude module, for listing its public names.
pub fn prelude_source(name: &str) -> Option<&'static str> {
    STDLIB.iter().find(|(n, _)| *n == name).map(|(_, src)| *src)
}

/// The constant every module is given at load time, holding its own source
/// location. The leading `_` makes it private to the module that declares it, so
/// each file reads its own and no import ever sees another's.
pub const MODULE_PATH_CONST: &str = "_PATH";

/// Declare `_PATH` at the top of `ast`. `location` is the module's absolute file
/// path when it has one on disk, and its diagnostic label (`<std/io>`,
/// `<plugin:...>`) when it does not -- a module with no file still answers the
/// question "where am I?" with something a human can read.
///
/// This is the loader's job rather than the parser's because only the loader
/// knows where a module came from: the same source text compiled from a
/// different directory must report a different `_PATH`.
pub fn inject_module_path(ast: &mut Module, location: &str, span: Span) {
    let decl = Stmt::Let {
        pat: Pattern::Binding(MODULE_PATH_CONST.to_string(), span),
        ty: Some(TypeExpr::Named("string".to_string(), span)),
        value: Some(Expr::Str(vec![StrSeg::Lit(location.to_string())], span)),
        is_const: true,
        span,
    };
    ast.items.insert(0, TopLevel::Stmt(decl));
}

/// A module's `_PATH` value: its canonical absolute path, falling back to the
/// path as written when the file cannot be canonicalized (it was deleted, or an
/// unsaved language-server buffer).
fn module_location(file: &Path) -> String {
    std::fs::canonicalize(file)
        .unwrap_or_else(|_| file.to_path_buf())
        .display()
        .to_string()
}

/// Whether an import path refers to a prelude module supplied as [`STDLIB`]
/// rather than a file on disk.
pub fn is_prelude_path(path: &[String]) -> bool {
    matches!(path, [single] if STDLIB.iter().any(|(name, _)| name == single))
}

/// The `std/`-relative key of an embedded nested module for a canonical import
/// path (`["std","net"]` -> `"net"`, `["std","collections","hashmap"]` ->
/// `"collections/hashmap"`), or `None` if the path does not start with `std`.
/// A key with no match in [`STDLIB_NESTED`] is simply not loaded (and
/// reported by `check_imports`), so prelude modules -- which are imported
/// without the `std.` prefix -- never collide here.
fn nested_key(path: &[String]) -> Option<String> {
    match path {
        [first, rest @ ..] if first == "std" && !rest.is_empty() => Some(rest.join("/")),
        _ => None,
    }
}

/// Load the embedded nested std modules (`std.collections`,
/// `std.collections.hashmap`) imported by `modules` or named in `extra_imports`
/// (the active document's imports, when it is kept separate from `modules`),
/// transitively (a nested module may import another). Returns the newly loaded
/// modules to append to the graph; nested modules that are not imported
/// anywhere are never loaded, so they are not part of the implicit prelude. An
/// import of a `std.<...>` path with no matching embedded module is left for
/// `check_imports` to report.
pub fn load_std_nested(
    modules: &[LoadedModule],
    extra_imports: &[Vec<String>],
    sources: &mut SourceMap,
) -> Vec<LoadedModule> {
    let mut loaded: HashSet<Vec<String>> = modules.iter().map(|m| m.path.clone()).collect();
    let mut out: Vec<LoadedModule> = Vec::new();
    // Seed the worklist from every module already in the graph plus the extras.
    let mut work: Vec<Vec<String>> = modules
        .iter()
        .flat_map(|m| m.ast.imports.iter().map(|imp| imp.path.clone()))
        .chain(extra_imports.iter().cloned())
        .collect();
    while let Some(path) = work.pop() {
        let Some(key) = nested_key(&path) else {
            continue;
        };
        if loaded.contains(&path) {
            continue;
        }
        let Some((_, src)) = STDLIB_NESTED.iter().find(|(k, _)| *k == key) else {
            continue; // unknown std module: reported by check_imports
        };
        let label = format!("<std/{key}>");
        let base = sources.add(None, label.clone(), (*src).to_string());
        // The embedded std sources are known-good, so a parse failure is a build
        // bug; skip on error rather than aborting the user's compile.
        let Ok(mut ast) = parse_with_base(src, base) else {
            continue;
        };
        inject_module_path(&mut ast, &label, Span::new(base, base));
        loaded.insert(path.clone());
        for imp in &ast.imports {
            work.push(imp.path.clone());
        }
        out.push(LoadedModule {
            is_prelude: false,
            path,
            ast,
        });
    }
    out
}

/// Each loaded source with the disjoint byte-offset base its spans were parsed
/// at, so a global span offset locates its file. Every file is lexed from
/// offset zero, but `parse_with_base` shifts each file's spans by its base; the
/// one-byte gap between files keeps an end-of-file span from colliding with the
/// next file's first byte.
#[derive(Clone, Default)]
pub struct SourceMap {
    next_base: usize,
    entries: Vec<SourceEntry>,
}

#[derive(Clone)]
struct SourceEntry {
    base: usize,
    /// `None` for an embedded prelude module (no file on disk).
    path: Option<PathBuf>,
    /// Display name for diagnostics: the file path, or `<std/name>` for an
    /// embedded prelude module.
    label: String,
    src: String,
}

/// One located global offset: the containing file (when it exists on disk), its
/// display label, its full source, and the file-local offset.
pub struct Located<'a> {
    pub path: Option<&'a Path>,
    pub label: &'a str,
    pub src: &'a str,
    pub local: usize,
}

impl SourceMap {
    /// Reserve a disjoint base for `src`, record it, and return the base to
    /// parse at.
    pub fn add(&mut self, path: Option<PathBuf>, label: String, src: String) -> usize {
        let base = self.next_base;
        self.next_base = base + src.len() + 1;
        self.entries.push(SourceEntry {
            base,
            path,
            label,
            src,
        });
        base
    }

    /// Locate the file containing global byte offset `off`.
    /// Every on-disk file this map read, in load order. Embedded sources (the
    /// prelude) carry no path and are skipped. The analysis cache stamps these
    /// to decide reuse.
    pub fn file_paths(&self) -> impl Iterator<Item = &std::path::Path> {
        self.entries.iter().filter_map(|e| e.path.as_deref())
    }

    /// Every source in load order, as `(base, text)`. The analysis cache hashes
    /// these to identify a module set by content.
    pub fn entries(&self) -> impl Iterator<Item = (usize, &str)> {
        self.entries.iter().map(|e| (e.base, e.src.as_str()))
    }

    pub fn locate(&self, off: usize) -> Option<Located<'_>> {
        self.entries.iter().find_map(|e| {
            (off >= e.base && off <= e.base + e.src.len()).then_some(Located {
                path: e.path.as_deref(),
                label: &e.label,
                src: &e.src,
                local: off - e.base,
            })
        })
    }
}

/// A non-fatal module-graph problem (missing import, dependency parse failure,
/// circular or private import), attributed to the span of the import in the
/// entry file that triggered the load -- so a diagnostic always lands in the
/// file the user is looking at, not in a transitive dependency.
#[derive(Clone, Debug)]
pub struct LoadError {
    pub message: String,
    pub span: Span,
}

/// Module roots beyond the project directory, from two environment variables
/// that may be set together:
///
/// - `BRASS_PACKAGES` (`name=/dir:name2=/dir2:...`), set by the package
///   manager: a name-keyed map. An import whose FIRST segment is a declared
///   name resolves under that entry's directory and nowhere else, so a
///   manifest scopes exactly which external modules a project sees.
/// - `BRASS_INCLUDE` (`/dir:/dir2:...`), set by the user or a distribution:
///   ordered open roots. Any module under an include path is importable as if
///   it sat next to the entry file; the project root is searched first, then
///   each include path in list order, so a local file shadows an include
///   module and earlier entries shadow later ones.
///
/// A package name binds its imports before any file search runs, so a
/// declared dependency cannot be shadowed by a same-named local file or
/// include module.
#[derive(Clone, Default)]
pub struct SearchPaths {
    pub packages: HashMap<String, PathBuf>,
    pub includes: Vec<PathBuf>,
}

impl SearchPaths {
    /// Read both environment variables, then append the distribution's
    /// implicit include entry (see [`distribution_libraries_dir`]) so every
    /// front end -- the compiler and the language server -- resolves imports
    /// identically. Malformed `BRASS_PACKAGES` entries (no `=`) and empty
    /// entries in either variable are skipped; unset variables contribute
    /// nothing. The implicit entry comes last, so explicit include paths and
    /// package declarations always win.
    pub fn from_env() -> Self {
        let packages = std::env::var("BRASS_PACKAGES")
            .unwrap_or_default()
            .split(':')
            .filter_map(|entry| {
                let (name, path) = entry.split_once('=')?;
                Some((name.to_string(), PathBuf::from(path)))
            })
            .collect();
        let mut includes: Vec<PathBuf> = std::env::var("BRASS_INCLUDE")
            .unwrap_or_default()
            .split(':')
            .filter(|s| !s.is_empty())
            .map(PathBuf::from)
            .collect();
        includes.extend(distribution_libraries_dir());
        SearchPaths { packages, includes }
    }
}

/// The `libraries/` directory a distributed toolchain ships beside its
/// `bin/` directory: `<dir of the running binary>/../libraries`, when it
/// exists, so the bundled libraries import with no environment setup
/// (`bin/brass` and `bin/czls` resolve to the same directory).
/// In-repo builds have no such directory (`target/debug/../libraries`), so
/// development runs see nothing implicit. Cached: the executable's location
/// cannot change within a process.
fn distribution_libraries_dir() -> Option<PathBuf> {
    static DIR: std::sync::OnceLock<Option<PathBuf>> = std::sync::OnceLock::new();
    DIR.get_or_init(|| {
        let exe = std::env::current_exe().ok()?;
        let dir = exe.parent()?.parent()?.join("libraries");
        dir.is_dir().then_some(dir)
    })
    .clone()
}

/// What a module path resolved to on disk: a `.cz` source file, or a native
/// plugin library serving the path as a synthesized module.
enum ModuleFile {
    Source(PathBuf),
    Plugin(PathBuf),
}

/// The `.cz` file or plugin library serving `segs` under the single root `r`
/// (a `.cz` file wins over a plugin library).
fn module_file_under(r: &Path, segs: &[String]) -> Option<ModuleFile> {
    let mut file = r.to_path_buf();
    for seg in segs {
        file.push(seg);
    }
    file.set_extension("cz");
    if file.is_file() {
        return Some(ModuleFile::Source(file));
    }
    crate::plugin::plugin_library_for(r, segs).map(ModuleFile::Plugin)
}

/// Find the file serving module path `segs`. A path whose first segment is a
/// declared package name looks ONLY under that package's directory -- a
/// declared dependency that lacks the module is an error, not a fallthrough.
/// Any other path searches the project `root` first, then each include
/// directory in order, so the first root that serves the path wins.
fn find_module_file(root: &Path, search: &SearchPaths, segs: &[String]) -> Option<ModuleFile> {
    if let Some(pkg_root) = segs.first().and_then(|s| search.packages.get(s.as_str())) {
        return module_file_under(pkg_root, segs);
    }
    std::iter::once(root)
        .chain(search.includes.iter().map(PathBuf::as_path))
        .find_map(|r| module_file_under(r, segs))
}

/// The source text serving module path `segs` as seen from `root`: the `.cz`
/// file's contents, or a native plugin library's synthesized wrapper module.
/// Resolution follows [`find_module_file`] (package directory, project root,
/// then include paths). Used by editor tooling to list a module's exports
/// without loading the whole graph.
pub fn module_source(root: &Path, search: &SearchPaths, segs: &[String]) -> Option<String> {
    match find_module_file(root, search, segs)? {
        ModuleFile::Source(file) => std::fs::read_to_string(file).ok(),
        ModuleFile::Plugin(lib) => crate::plugin::synthesize_plugin_module(&lib).ok(),
    }
}

/// Parse the embedded prelude into `sources`, returning its modules. The
/// prelude is known-good, so a parse failure is a build bug reported as the
/// rendered message.
pub fn parse_stdlib(sources: &mut SourceMap) -> Result<Vec<LoadedModule>, String> {
    let mut modules = Vec::with_capacity(STDLIB.len());
    for (name, src) in STDLIB {
        let label = format!("<std/{name}>");
        let base = sources.add(None, label.clone(), (*src).to_string());
        let mut ast = parse_with_base(src, base).map_err(|e| {
            let (line, col) = line_col(src, e.span.lo - base);
            format!("{label}:{line}:{col}: parse error: {}", e.message)
        })?;
        inject_module_path(&mut ast, &label, Span::new(base, base));
        let mut path = vec!["std".to_string()];
        path.extend(name.split('/').map(str::to_string));
        modules.push(LoadedModule {
            is_prelude: true,
            path,
            ast,
        });
    }
    Ok(modules)
}

/// Resolve an import path, written relative to the importing file, to the
/// imported module's canonical path. A path whose first segment is a declared
/// package name is already canonical (the name roots it). Every other import
/// is relative to the importing file's own directory `base`, so `import b`
/// from `modules/a.cz` refers to `modules/b.cz`; the relative form is looked
/// up across the project root and every include path. When the relative form
/// names no file and `base` is non-empty, the path as written is tried
/// instead, so a nested module can still reach a top-level include library
/// (`import geometry` from `modules/a.cz`). A `std.*` path or a bare prelude
/// module is global rather than file-relative and returns `None`, so the
/// caller leaves it untouched and does not load it from disk.
///
/// An unresolved path keeps its relative form, so the load step reports the
/// missing module at the location the import most likely meant.
fn relativize(
    base: &[String],
    imp_path: &[String],
    root: &Path,
    search: &SearchPaths,
) -> Option<Vec<String>> {
    if imp_path.first().map(|s| s == "std").unwrap_or(false) || is_prelude_path(imp_path) {
        return None;
    }
    if imp_path
        .first()
        .is_some_and(|s| search.packages.contains_key(s.as_str()))
    {
        return Some(imp_path.to_vec());
    }
    let mut canonical = base.to_vec();
    canonical.extend_from_slice(imp_path);
    if base.is_empty() || find_module_file(root, search, &canonical).is_some() {
        return Some(canonical);
    }
    if find_module_file(root, search, imp_path).is_some() {
        return Some(imp_path.to_vec());
    }
    Some(canonical)
}

/// Classify a brace-less import (`import a.b` / `import a.b.X`) now that the
/// importing file's directory is known: when the full path names a module -- a
/// file under `root`, a package, or an include path, a prelude module, or an
/// embedded nested std module -- it is a MODULE import, used qualified through
/// its last segment (`import geometry.vec` -> `vec.dot(..)`); otherwise its
/// last segment is a single name imported from the enclosing module (`import
/// geometry.vec.dot` == `import geometry.vec.{ dot }`). A path that names
/// neither stays a module import so the load step reports the missing module
/// at this import.
fn classify_bare(base: &[String], root: &Path, imp: &mut ImportDecl, search: &SearchPaths) {
    let module_exists = |path: &[String]| -> bool {
        if is_prelude_path(path) {
            return true;
        }
        if let Some(key) = nested_key(path) {
            return STDLIB_NESTED.iter().any(|(k, _)| *k == key);
        }
        if path.first().is_some_and(|s| s == "std") {
            return false;
        }
        // Mirror `relativize`: a package name roots the path as written;
        // otherwise the relative form first, then -- from a nested module --
        // the path as written, so both agree on what exists.
        if path
            .first()
            .is_some_and(|s| search.packages.contains_key(s.as_str()))
        {
            return find_module_file(root, search, path).is_some();
        }
        let mut full = base.to_vec();
        full.extend_from_slice(path);
        find_module_file(root, search, &full).is_some()
            || (!base.is_empty() && find_module_file(root, search, path).is_some())
    };
    if module_exists(&imp.path) {
        // An explicit `as` alias takes precedence over the last-segment default.
        if !imp.explicit_alias {
            imp.alias = imp.path.last().cloned();
        }
        return;
    }
    if imp.path.len() >= 2 && module_exists(&imp.path[..imp.path.len() - 1]) {
        let name = imp.path.pop().expect("checked len >= 2");
        // `import a.b.X as Y`: the explicit alias renames the single name.
        let imported = if imp.explicit_alias {
            let local = imp.alias.take().unwrap_or_else(|| name.clone());
            imp.explicit_alias = false;
            ImportedName {
                remote: name,
                local,
                span: imp.span,
            }
        } else {
            ImportedName::plain(name, imp.span)
        };
        imp.names.push(imported);
        imp.bare = false;
        return;
    }
    // Unknown module — keep the path as-is for downstream error reporting.
    if !imp.explicit_alias {
        imp.alias = imp.path.last().cloned();
    }
}

/// Rewrite each import's path from importer-relative to canonical form in
/// place -- so the loaded modules and downstream name resolution share one
/// path per file -- and return the canonical paths of the file modules to
/// load, each with the span of the import that requested it (for error
/// attribution). Brace-less imports are classified against the same roots
/// first (see [`classify_bare`]).
pub fn canonicalize_imports(
    base: &[String],
    root: &Path,
    imports: &mut [ImportDecl],
    search: &SearchPaths,
) -> Vec<(Vec<String>, Span)> {
    let mut targets = Vec::new();
    for imp in imports.iter_mut() {
        if imp.bare {
            classify_bare(base, root, imp, search);
        }
        if let Some(canonical) = relativize(base, &imp.path, root, search) {
            imp.path = canonical.clone();
            targets.push((canonical, imp.span));
        }
    }
    targets
}

/// Load the module at canonical `path` and, transitively, every module it
/// imports, pushing each onto `out`. Problems are collected into `errors`
/// rather than aborting, so one bad dependency does not hide the rest:
/// graph-level problems (missing file, privacy, cycle) are attributed to
/// `trigger_span` (the entry-file import that asked for this subgraph), while
/// a dependency's own syntax errors keep their in-file spans. `std`/prelude
/// paths never arrive here (they are filtered out as non-file modules during
/// canonicalization).
///
/// The file serving `path` is found by [`find_module_file`]: a declared
/// package's directory when the first segment names one, otherwise the
/// project `root` first and then each include path in order.
#[allow(clippy::too_many_arguments)]
pub fn load_module(
    path: &[String],
    root: &Path,
    sources: &mut SourceMap,
    visited: &mut HashSet<String>,
    stack: &mut HashSet<String>,
    out: &mut Vec<LoadedModule>,
    trigger_span: Span,
    errors: &mut Vec<LoadError>,
    search: &SearchPaths,
) {
    let key = path.join(".");
    if crate::is_private_module(path) {
        errors.push(LoadError {
            message: format!("cannot import private module `{key}`"),
            span: trigger_span,
        });
        return;
    }
    if visited.contains(&key) {
        return;
    }
    if !stack.insert(key.clone()) {
        errors.push(LoadError {
            message: format!("circular import involving `{key}`"),
            span: trigger_span,
        });
        return;
    }

    let (file, src) = match find_module_file(root, search, path) {
        // A native plugin library may serve the path instead of a `.cz` file
        // (`plugins/math.so` for `import plugins.math`), as a module
        // synthesized from the plugin's manifest.
        Some(ModuleFile::Plugin(lib)) => {
            match crate::plugin::synthesize_plugin_module(&lib) {
                Ok(src) => load_synthesized(&lib, src, path, sources, out, trigger_span, errors),
                Err(message) => errors.push(LoadError {
                    message,
                    span: trigger_span,
                }),
            }
            stack.remove(&key);
            visited.insert(key);
            return;
        }
        Some(ModuleFile::Source(file)) => match std::fs::read_to_string(&file) {
            Ok(src) => (file, src),
            Err(e) => {
                errors.push(LoadError {
                    message: format!("cannot read module `{key}` (`{}`): {e}", file.display()),
                    span: trigger_span,
                });
                stack.remove(&key);
                visited.insert(key);
                return;
            }
        },
        None => {
            // Point at the expected location: a package-rooted path expects
            // its file under the declared package's directory; anything else
            // expects the project-root location, with a note when include
            // paths were searched too.
            let pkg_root = path.first().and_then(|s| search.packages.get(s.as_str()));
            let mut expected = pkg_root.map(PathBuf::from).unwrap_or(root.to_path_buf());
            for seg in path {
                expected.push(seg);
            }
            expected.set_extension("cz");
            let searched = if pkg_root.is_some() || search.includes.is_empty() {
                String::new()
            } else {
                format!("; also searched {} include path(s)", search.includes.len())
            };
            errors.push(LoadError {
                message: format!(
                    "cannot find module `{key}` (expected `{}`{searched})",
                    expected.display()
                ),
                span: trigger_span,
            });
            stack.remove(&key);
            visited.insert(key);
            return;
        }
    };
    let label = file.display().to_string();
    let location = module_location(&file);
    let base = sources.add(Some(file), label, src.clone());
    let (ast, parse_errors) = brass_parser::parse_recovering(&src, base);
    if !parse_errors.is_empty() {
        for e in parse_errors {
            errors.push(LoadError {
                message: format!("syntax error: {}", e.message),
                span: e.span,
            });
        }
        stack.remove(&key);
        visited.insert(key);
        return;
    }
    let mut ast = ast;
    inject_module_path(&mut ast, &location, Span::new(base, base));
    let dir = path[..path.len() - 1].to_vec();
    for (target, _) in canonicalize_imports(&dir, root, &mut ast.imports, search) {
        load_module(
            &target,
            root,
            sources,
            visited,
            stack,
            out,
            trigger_span,
            errors,
            search,
        );
    }
    stack.remove(&key);
    visited.insert(key.clone());
    out.push(LoadedModule {
        is_prelude: false,
        path: path.to_vec(),
        ast,
    });
}

/// Parse a module synthesized from a plugin manifest and push it. The source
/// is generated, so a parse failure is a synthesis bug, reported (with the
/// offending text's label) rather than crashing the front end.
fn load_synthesized(
    lib: &Path,
    src: String,
    path: &[String],
    sources: &mut SourceMap,
    out: &mut Vec<LoadedModule>,
    trigger_span: Span,
    errors: &mut Vec<LoadError>,
) {
    let label = format!("<plugin:{}>", lib.display());
    let base = sources.add(None, label.clone(), src.clone());
    match parse_with_base(&src, base) {
        Ok(mut ast) => {
            inject_module_path(&mut ast, &label, Span::new(base, base));
            out.push(LoadedModule {
                is_prelude: false,
                path: path.to_vec(),
                ast,
            })
        }
        Err(e) => errors.push(LoadError {
            message: format!(
                "internal: synthesized plugin module `{label}` failed to parse: {}",
                e.message
            ),
            span: trigger_span,
        }),
    }
}
