//! Native plugin modules: an `import` whose target is a plugin library
//! (`plugins/math.so`) instead of a `.cz` file.
//!
//! The library's manifest (function names, signatures, Rust doc comments; see
//! `brass_plugin_host`) is turned into ordinary Brass source: one fully
//! annotated wrapper function per exposed function, carrying the doc comment,
//! whose body forwards to the `_plugin_call_*` / `_plugin_fcall_*` runtime
//! builtins with the library path, the function name, and the encoded
//! signature. Because the synthesized module is real source, the whole
//! front end -- type checking, visibility, hover, completion -- treats plugin
//! functions exactly like `.cz` functions.

use std::collections::HashSet;
use std::path::{Path, PathBuf};

use brass_plugin_host::ValueType;

/// The plugin library serving module path `segs` under `effective_root`, if
/// one exists: the last segment names the library file (`name.so` or the
/// `cdylib` output name `libname.so`, platform-suffixed), the leading
/// segments its directory. Also used by editor tooling to list a plugin
/// module's functions without loading the whole module graph.
pub fn plugin_library_for(effective_root: &Path, segs: &[String]) -> Option<PathBuf> {
    let (last, dir_segs) = segs.split_last()?;
    let mut dir = effective_root.to_path_buf();
    for s in dir_segs {
        dir.push(s);
    }
    brass_plugin_host::find_library(&dir, last)
}

/// Load the plugin at `lib` and synthesize its module source. Errors are
/// load-level (unreadable library, ABI mismatch, malformed manifest).
pub fn synthesize_plugin_module(lib: &Path) -> Result<String, String> {
    let manifest = brass_plugin_host::load_manifest(lib)?;
    // The runtime re-opens the library by this exact string; canonical form
    // keeps it stable regardless of the importing file's location.
    let lib_path = lib
        .canonicalize()
        .map_err(|e| format!("cannot resolve plugin path `{}`: {e}", lib.display()))?;
    synthesize_source(&manifest, &lib_path.to_string_lossy())
}

/// The module source for `manifest`, whose library the wrappers reach through
/// the embedded `lib_str`. Separated from loading so the synthesis rules
/// (name/parameter renaming, doc and literal escaping) are testable without a
/// library on disk.
pub fn synthesize_source(
    manifest: &brass_plugin_host::PluginManifest,
    lib_str: &str,
) -> Result<String, String> {
    let mut src = format!(
        "// Native plugin module synthesized from `{lib_str}`.\n// Generated by the loader; the \
         functions below forward to the plugin.\n"
    );
    let mut emitted: HashSet<String> = HashSet::new();
    for f in &manifest.functions {
        src.push('\n');
        if let Some(doc) = &f.doc {
            src.push_str(&format!("/**\n{}\n*/\n", sanitize_doc(doc)));
        }
        let params = f
            .params
            .iter()
            .map(|(n, t)| format!("{}: {}", safe_param(n), brass_type(t)))
            .collect::<Vec<_>>()
            .join(", ");
        let args = f
            .params
            .iter()
            .map(|(n, _)| format!(", {}", safe_param(n)))
            .collect::<String>();
        let sig = sig_string(f);
        // Fallible functions return the builtin's `Result` whole, so the
        // wrapper is fallible; a fallible void return has no annotated form
        // and is left to return-type inference.
        let ret = match (f.fallible, &f.ret) {
            (_, ValueType::Void) => String::new(),
            (false, t) => format!(" -> {}", brass_type(t)),
            (true, t) => format!(" -> {}!", brass_type(t)),
        };
        let callee = format!(
            "_plugin_{}call_{}",
            if f.fallible { "f" } else { "" },
            f.ret.code()
        );
        // The plugin's own name goes into the call, so a renamed wrapper still
        // dispatches to the function the manifest declared.
        let call = format!(
            "{callee}(\"{}\", \"{}\", \"{}\"{args})",
            escape(lib_str),
            escape(&f.name),
            escape(&sig)
        );
        let body = if f.ret == ValueType::Void && !f.fallible {
            format!("    {call}\n")
        } else {
            format!("    return {call}\n")
        };
        let wrapper = safe_function_name(&f.name);
        if !emitted.insert(wrapper.clone()) {
            return Err(format!(
                "plugin `{lib_str}`, function `{}`: its Brass name `{wrapper}` collides with \
                 another exported function",
                f.name
            ));
        }
        src.push_str(&format!("fun {wrapper}({params}){ret} {{\n{body}}}\n"));
    }
    Ok(src)
}

/// The manifest signature string of `f` (`"ii:i!"`), re-encoded for the
/// runtime call so argument marshaling needs no second manifest read.
fn sig_string(f: &brass_plugin_host::PluginFunction) -> String {
    let mut s = String::new();
    for (_, t) in &f.params {
        t.write_code(&mut s);
    }
    s.push(':');
    f.ret.write_code(&mut s);
    if f.fallible {
        s.push('!');
    }
    s
}

/// The Brass spelling of a plugin value type. An array is its element's
/// spelling with `[]` appended, so `Array(Array(Str))` reads `string[][]`.
fn brass_type(t: &ValueType) -> String {
    match t {
        ValueType::Void => "void".to_string(),
        ValueType::Bool => "bool".to_string(),
        ValueType::Int => "int64".to_string(),
        ValueType::Float => "float64".to_string(),
        ValueType::Str => "string".to_string(),
        ValueType::Bytes => "uint8[]".to_string(),
        ValueType::Array(elem) => format!("{}[]", brass_type(elem)),
    }
}

/// A parameter name safe to use in synthesized source: a Rust identifier that
/// collides with a Brass keyword gets a trailing `_`. The keyword set is the
/// lexer's own, so this guard cannot drift from the grammar.
fn safe_param(name: &str) -> String {
    if brass_parser::is_keyword(name) {
        format!("{name}_")
    } else {
        name.to_string()
    }
}

/// The Brass name of a plugin function's wrapper. Beyond keywords, a
/// definition may not take one of the names the runtime owns (`len`, `error`,
/// ...), so those are renamed too; dispatch is unaffected because the call
/// carries the manifest name as a string.
fn safe_function_name(name: &str) -> String {
    if brass_parser::is_keyword(name) || brass_hir::RESERVED_FUNCTION_NAMES.contains(&name) {
        format!("{name}_")
    } else {
        name.to_string()
    }
}

/// Neutralize comment delimiters in a doc comment before it is embedded in a
/// `/** ... */` block. Brass's block comments NEST, so a stray `/*` opens a
/// depth the closer never balances -- both delimiters have to go, and the
/// closer first so an overlapping `/*/` is fully covered.
fn sanitize_doc(doc: &str) -> String {
    doc.replace("*/", "* /").replace("/*", "/ *")
}

/// Escape a string for a synthesized Brass string literal. `{` opens
/// interpolation, so it escapes alongside the backslash and the quote.
fn escape(s: &str) -> String {
    s.replace('\\', "\\\\")
        .replace('"', "\\\"")
        .replace('{', "\\{")
}
