//! Embeds the standard library. The `std/` tree is enumerated at build time
//! and written to `$OUT_DIR/stdlib.rs` as two tables of
//! `(module key, include_str!(source))` pairs:
//!
//! - `STDLIB` -- every `.pp` under `std/prelude/`, keyed by file stem
//!   (`io`, `array`, ...): the implicit prelude.
//! - `STDLIB_NESTED` -- every other `.pp` under `std/`, keyed by its
//!   `std/`-relative path without the extension (`net`, `collections`,
//!   `data/json`): import-only modules.
//!
//! `loader.rs` pulls the tables in with `include!`, so adding a module to the
//! standard library is just adding a file -- no Rust edit. The generated
//! `include_str!` paths are anchored at `CARGO_MANIFEST_DIR` (they cannot be
//! relative: a relative path inside the generated file would resolve against
//! `OUT_DIR`), and they make the compiler re-embed a module when its source
//! changes; this script itself re-runs only when the tree's shape changes.

use std::env;
use std::fs;
use std::path::{Path, PathBuf};

/// Every `.pp` under `dir` (recursively, `skip` pruned), as the pair of its
/// `root`-relative extensionless key and its `include_base`-relative include
/// path (the repo root, so paths read `std/...`), sorted by key so the
/// generated tables are deterministic.
fn collect_pp(
    root: &Path,
    include_base: &Path,
    dir: &Path,
    skip: Option<&Path>,
) -> Vec<(String, String)> {
    let mut out = Vec::new();
    let mut stack = vec![dir.to_path_buf()];
    while let Some(d) = stack.pop() {
        for entry in fs::read_dir(&d).expect("read std dir") {
            let path = entry.expect("read std dir entry").path();
            if Some(path.as_path()) == skip {
                continue;
            }
            if path.is_dir() {
                stack.push(path);
            } else if path.extension().is_some_and(|e| e == "pp") {
                let key = path
                    .strip_prefix(root)
                    .expect("under root")
                    .with_extension("")
                    .to_string_lossy()
                    .replace('\\', "/");
                let include = path
                    .strip_prefix(include_base)
                    .expect("under the repo root")
                    .to_string_lossy()
                    .replace('\\', "/");
                out.push((key, include));
            }
        }
    }
    out.sort();
    out
}

fn write_table(out: &mut String, name: &str, doc: &str, entries: &[(String, String)]) {
    for line in doc.lines() {
        out.push_str("/// ");
        out.push_str(line);
        out.push('\n');
    }
    out.push_str(&format!("pub const {name}: &[(&str, &str)] = &[\n"));
    for (key, include) in entries {
        out.push_str(&format!(
            "    ({key:?}, include_str!(concat!(env!(\"CARGO_MANIFEST_DIR\"), \"/../../{include}\"))),\n"
        ));
    }
    out.push_str("];\n");
}

fn main() {
    let manifest = PathBuf::from(env::var("CARGO_MANIFEST_DIR").expect("CARGO_MANIFEST_DIR"));
    let std_dir = manifest.join("../../std");
    // Adding/removing/renaming a module re-runs this script (cargo scans the
    // directory); editing one only recompiles through include_str!.
    println!("cargo:rerun-if-changed={}", std_dir.display());

    let repo_root = std_dir.parent().expect("std has a parent").to_path_buf();
    let prelude_dir = std_dir.join("prelude");
    let prelude = collect_pp(&prelude_dir, &repo_root, &prelude_dir, None);
    let nested = collect_pp(&std_dir, &repo_root, &std_dir, Some(prelude_dir.as_path()));
    assert!(
        !prelude.is_empty(),
        "no prelude modules found under {}",
        prelude_dir.display()
    );

    let mut src = String::new();
    write_table(
        &mut src,
        "STDLIB",
        "Embedded prelude modules (`std/prelude/*.pp`), always in scope with no\n\
         import needed. Only these are the implicit prelude. Generated by\n\
         build.rs from the `std/` tree.",
        &prelude,
    );
    src.push('\n');
    write_table(
        &mut src,
        "STDLIB_NESTED",
        "Embedded standard-library modules BELOW `std` (`std.collections`,\n\
         `std.collections`, `std.data.json`, ...): every non-prelude `.pp`\n\
         under `std/`. Not in the implicit prelude -- their names are in scope\n\
         only after an explicit `import std.<path>.{ Name }`, at which point\n\
         the module is loaded on demand (`load_std_nested`). Keyed by the\n\
         module's dotted path relative to `std` (segments joined with `/`).\n\
         Generated by build.rs from the `std/` tree.",
        &nested,
    );

    let out = PathBuf::from(env::var("OUT_DIR").expect("OUT_DIR")).join("stdlib.rs");
    fs::write(&out, src).expect("write stdlib.rs");
}
